services:
  - type: web
    name: dynamous-python-agent
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn sample_supabase_agent:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        value: https://your_url.supabase.co
      - key: SUPABASE_SERVICE_KEY  
        value: your_super_secret_key
      - key: API_BEARER_TOKEN
        value: choose-a-secure-random-token
      - key: PORT
        value: 10000